In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import string
import nltk

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\gurug\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\gurug\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\gurug\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\gurug\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\gurug\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\gurug\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [10]:
df = pd.read_excel("amazon.xlsx")

df.head()

,Star,HelpFul,Title,Review
0,5,0,looks great,Happy with it
1,5,0,Pattern did not align between the two panels.,Good quality material however the panels are m...
2,5,0,Imagery is stretched. Still fun.,Product was fun for bedroom windows.<br />Imag...
3,5,0,Que se ven elegantes muy finas,Lo unico que me gustaria es que sean un poco ...
4,5,0,Wow great purchase,Great bang for the buck I can't believe the qu...

In [11]:
print(df.shape)

df.info()

df.isnull().sum()

(5611, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5611 entries, 0 to 5610
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Star     5611 non-null   int64
 1   HelpFul  5611 non-null   int64
 2   Title    5559 non-null   object
 3   Review   5593 non-null   object
dtypes: int64(2), object(2)
memory usage: 175.5+ KB

(5611, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5611 entries, 0 to 5610
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Star     5611 non-null   int64
 1   HelpFul  5611 non-null   int64
 2   Title    5559 non-null   object
 3   Review   5593 non-null   object
dtypes: int64(2), object(2)
memory usage: 175.5+ KB

Star        0
HelpFul     0
Title      52
Review     18
dtype: int64

In [12]:
df = df[['Star','Review']]

df.head()

   Star                                             Review
0     5                                      Happy with it
1     5  Good quality material however the panels are m...
2     5  Product was fun for bedroom windows.<br />Imag...
3     5   Lo unico que me gustaria es que sean un poco ...
4     5  Great bang for the buck I can't believe the qu...

In [13]:
df = df[df['Star'] != 3]

df['label'] = df['Star'].apply(lambda x: 1 if x >= 4 else 0)

df.head()

   Star                                             Review  label
0     5                                      Happy with it      1
1     5  Good quality material however the panels are m...      1
2     5  Product was fun for bedroom windows.<br />Imag...      1
3     5   Lo unico que me gustaria es que sean un poco ...      1
4     5  Great bang for the buck I can't believe the qu...      1

In [14]:
df["clean_text"] = df["Review"].astype(str).str.lower()

df.head()

,Star,Review,label,clean_text
0,5,Happy with it,1,happy with it
1,5,Good quality material however the panels are m...,1,good quality material however the panels are m...
2,5,Product was fun for bedroom windows.<br />Imag...,1,product was fun for bedroom windows.<br />imag...
3,5,Lo unico que me gustaria es que sean un poco ...,1,lo unico que me gustaria es que sean un poco ...
4,5,Great bang for the buck I can't believe the qu...,1,great bang for the buck i can't believe the qu...

In [15]:
df["clean_text"] = df["clean_text"].str.replace(f"[{string.punctuation}]", "", regex=True)

df.head()

,Star,Review,label,clean_text
0,5,Happy with it,1,happy with it
1,5,Good quality material however the panels are m...,1,good quality material however the panels are m...
2,5,Product was fun for bedroom windows.<br />Imag...,1,product was fun for bedroom windowsbr imagery ...
3,5,Lo unico que me gustaria es que sean un poco ...,1,lo unico que me gustaria es que sean un poco ...
4,5,Great bang for the buck I can't believe the qu...,1,great bang for the buck i cant believe the qua...

In [16]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [17]:
df["tokens"] = df["clean_text"].apply(word_tokenize)

df.head()

,Star,Review,label,clean_text,tokens
0,5,Happy with it,1,happy with it,"[happy, with, it]"
1,5,Good quality material however the panels are m...,1,good quality material however the panels are m...,"[good, quality, material, however, the, panels..."
2,5,Product was fun for bedroom windows.<br />Imag...,1,product was fun for bedroom windowsbr imagery ...,"[product, was, fun, for, bedroom, windowsbr, i..."
3,5,Lo unico que me gustaria es que sean un poco ...,1,lo unico que me gustaria es que sean un poco ...,"[lo, unico, que, me, gustaria, es, que, sean, ..."
4,5,Great bang for the buck I can't believe the qu...,1,great bang for the buck i cant believe the qua...,"[great, bang, for, the, buck, i, cant, believe..."

In [18]:
stop_words = set(stopwords.words("english"))

df["tokens"] = df["tokens"].apply(
    lambda words: [word for word in words if word not in stop_words]
)

df.head()

,Star,Review,label,clean_text,tokens
0,5,Happy with it,1,happy with it,[happy]
1,5,Good quality material however the panels are m...,1,good quality material however the panels are m...,"[good, quality, material, however, panels, mis..."
2,5,Product was fun for bedroom windows.<br />Imag...,1,product was fun for bedroom windowsbr imagery ...,"[product, fun, bedroom, windowsbr, imagery, bi..."
3,5,Lo unico que me gustaria es que sean un poco ...,1,lo unico que me gustaria es que sean un poco ...,"[lo, unico, que, gustaria, es, que, sean, un, ..."
4,5,Great bang for the buck I can't believe the qu...,1,great bang for the buck i cant believe the qua...,"[great, bang, buck, cant, believe, quality, ma..."

In [19]:
stop_words = set(stopwords.words("english"))

df["tokens"] = df["tokens"].apply(
    lambda words: [word for word in words if word not in stop_words]
)

df.head()

,Star,Review,label,clean_text,tokens
0,5,Happy with it,1,happy with it,[happy]
1,5,Good quality material however the panels are m...,1,good quality material however the panels are m...,"[good, quality, material, however, panels, mis..."
2,5,Product was fun for bedroom windows.<br />Imag...,1,product was fun for bedroom windowsbr imagery ...,"[product, fun, bedroom, windowsbr, imagery, bi..."
3,5,Lo unico que me gustaria es que sean un poco ...,1,lo unico que me gustaria es que sean un poco ...,"[lo, unico, que, gustaria, es, que, sean, un, ..."
4,5,Great bang for the buck I can't believe the qu...,1,great bang for the buck i cant believe the qua...,"[great, bang, buck, cant, believe, quality, ma..."

In [20]:
lemmatizer = WordNetLemmatizer()

df["lemma"] = df["tokens"].apply(
    lambda words: [lemmatizer.lemmatize(word) for word in words]
)

df.head()

,Star,Review,label,clean_text,tokens,lemma
0,5,Happy with it,1,happy with it,[happy],[happy]
1,5,Good quality material however the panels are m...,1,good quality material however the panels are m...,"[good, quality, material, however, panels, mis...","[good, quality, material, however, panel, mism..."
2,5,Product was fun for bedroom windows.<br />Imag...,1,product was fun for bedroom windowsbr imagery ...,"[product, fun, bedroom, windowsbr, imagery, bi...","[product, fun, bedroom, windowsbr, imagery, bi..."
3,5,Lo unico que me gustaria es que sean un poco ...,1,lo unico que me gustaria es que sean un poco ...,"[lo, unico, que, gustaria, es, que, sean, un, ...","[lo, unico, que, gustaria, e, que, sean, un, p..."
4,5,Great bang for the buck I can't believe the qu...,1,great bang for the buck i cant believe the qua...,"[great, bang, buck, cant, believe, quality, ma...","[great, bang, buck, cant, believe, quality, ma..."

In [21]:
df["preprocessed_text"] = df["lemma"].apply(lambda words: " ".join(words))

df.head()

,Star,Review,label,clean_text,tokens,lemma,preprocessed_text
0,5,Happy with it,1,happy with it,[happy],[happy],happy
1,5,Good quality material however the panels are m...,1,good quality material however the panels are m...,"[good, quality, material, however, panels, mis...","[good, quality, material, however, panel, mism...",good quality material however panel mismatched
2,5,Product was fun for bedroom windows.<br />Imag...,1,product was fun for bedroom windowsbr imagery ...,"[product, fun, bedroom, windowsbr, imagery, bi...","[product, fun, bedroom, windowsbr, imagery, bi...",product fun bedroom windowsbr imagery bit stre...
3,5,Lo unico que me gustaria es que sean un poco ...,1,lo unico que me gustaria es que sean un poco ...,"[lo, unico, que, gustaria, es, que, sean, un, ...","[lo, unico, que, gustaria, e, que, sean, un, p...",lo unico que gustaria e que sean un poco ma la...
4,5,Great bang for the buck I can't believe the qu...,1,great bang for the buck i cant believe the qua...,"[great, bang, buck, cant, believe, quality, ma...","[great, bang, buck, cant, believe, quality, ma...",great bang buck cant believe quality material ...

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)

tfidf_features = vectorizer.fit_transform(df["preprocessed_text"])

tfidf_df = pd.DataFrame(
    tfidf_features.toarray(),
    columns=vectorizer.get_feature_names_out()
)

tfidf_df.head()

,10,100,1000,102,104,106,107,108,10884,108x108,...,youre,youth,youve,yr,yrsbecome,yuck,yuckjust,zen,zoom,zoomed
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
X = tfidf_df

y = df["label"]

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [26]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [27]:
y_pred = model.predict(X_test)

y_pred

array([1, 1, 1, ..., 1, 1, 1], shape=(1060,))

In [28]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy =", accuracy)

Accuracy = 0.9037735849056604

In [29]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[ 24  97]
 [  5 934]]

In [30]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.20      0.32       121
           1       0.91      0.99      0.95       939

    accuracy                           0.90      1060
   macro avg       0.87      0.60      0.63      1060
weighted avg       0.90      0.90      0.88      1060

In [31]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.20      0.32       121
           1       0.91      0.99      0.95       939

    accuracy                           0.90      1060
   macro avg       0.87      0.60      0.63      1060
weighted avg       0.90      0.90      0.88      1060

In [32]:
new_review = [
    "This product is amazing and worth buying."
]

In [33]:
new_review = [new_review[0].lower()]

new_review = [new_review[0].translate(str.maketrans('', '', string.punctuation))]

tokens = word_tokenize(new_review[0])

tokens = [word for word in tokens if word not in stop_words]

tokens = [lemmatizer.lemmatize(word) for word in tokens]

processed_review = " ".join(tokens)

processed_review

'product amazing worth buying'

In [34]:
review_vector = vectorizer.transform([processed_review])

prediction = model.predict(review_vector)

if prediction[0] == 1:
    print("Positive Review 😊")
else:
    print("Negative Review 😞")

Positive Review 😊

C:\Users\gurug\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(